---
- name: demonstrate using ansible facts
  hosts: local_servers
  gather_facts: true
  tasks:
    - name: run lsblk
      ansible.builtin.shell: 'lsblk -nd --output NAME'
      register: lsblk_data

    - name: show lsblk_data
      anisble.builtin.debug:
        var: lsblk_data

    - name: show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts['devices'] | to_yaml