---
- name: Use json filters to collect data from a Variable.
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: collect json data and create a varible with it.
      ansible.builtin.uri:
        url: http://localhost:8080/output.json
      register: domain_definition

    - name: Display all server ports and names from cluster1
      ansible.builtin.debug:
        var: item
      loop: "{{ domain_definition | community.general.json_query(server_name_cluster1_query) }}"
      vars:
        server_name_cluster1_query: "json.domain.server[?cluster=='cluster2'].{name: name, port: port}"
    - name: Display all ports from cluster1
      ansible.builtin.debug:
        msg: "{{ domain_definition | to_json | from_json | community.general.json_query(server_name_query) }}"
      vars:
        server_name_query: "domain.server[?contains(name,'server1')].port"

...
# Works based on https://docs.ansible.com/ansible/latest/collections/community/general/docsite/filter_guide_selecting_json_data.html