---
- name: Create an inventory 
  hosts: localhost
  tasks:
    - name: build an inventory
      add_host:
        hostname: "{{ item }}"
        groups:
          - my_group
      loop: "{{ HostList }}"

---
- name: demonstrate using inputs to run commands and output their information
  hosts: my_group
  gather_facts: true
  become: true
  vars_prompt:
    - name: my_command
      prompt: What is your command?
      private: false

  pre_tasks:
    - name: run a command
      ansible.builtin.command: "{{ my_command }}"
      register: command_output
      ignore_errors: true
    
    - name: show output
      ansible.builtin.debug:
        var: command_output

    - name: show output
      ansible.builtin.debug:
        var: command_output.stdout

    - name: print create_ticket variable
      ansible.builtin.set_fact:
        my_command_inforamtion: "{{ command_output }}"
    - name: store output

      ansible.builtin.copy:
        content: "{{ my_command_inforamtion }}"
        dest: /tmp/myfile.json
        mode: 0777
