---
- hosts: mygroup
  connection: local
  tasks:
    - name: Create ticket for builder
      ansible.builtin.uri:
        headers:
          Authorization: Bearer {{ myteam_jira_token }}
          Accept: application/json
        url: "https://tickets.example.com/rest/api/2/issue"
        method: "POST"
        status_code: 201
        body_format: json
        body: "{{ lookup('template', 'templates/uri_body.json') }}"
      register: created_ticket

    - name: print create_ticket variable
      ansible.builtin.debug:
        var: created_ticket

    - name: print create_ticket variable
      ansible.builtin.set_fact:
        my_ticket_inforamtion: "{{ created_ticket | to_nice_json }}"

    - name: store output
      ansible.builtin.copy:
        content: "{{ my_ticket_inforamtion }}"
        dest: /tmp/myfile.json
        mode: 0777

