---
installed_packages:
  - vim
  - python3

gitolite_conf_repos:
  - name: "repo northstar/[a-zA-Z0-9].*"
    permissions:
      - "RW helloworld\\.[0-9]+\\.[0-9]+$ = user1"
      - "RW helloworld\\.[0-9]+\\.[0-9]+$ = user2"
      - "RW helloworld\\.[0-9]+\\.[0-9]+$ = user3"

gitolite_conf_url: https://raw.githubusercontent.com/nicholasburr/Ansible-Demos/main/endpoints/list1.txt